// pages/index.js
import React, { useState, useEffect } from "react";
import Head from "next/head";

export default function ResumeBuilderLanding() {
  const [isVisible, setIsVisible] = useState(false);
  const [hoverButton, setHoverButton] = useState(false);
  const [animateItems, setAnimateItems] = useState([
    false,
    false,
    false,
    false,
  ]);

  useEffect(() => {
    // Set initial visibility after a short delay
    const timer = setTimeout(() => {
      setIsVisible(true);
    }, 100);

    // Stagger the list item animations
    const timers = [];
    [600, 800, 1000, 1200].forEach((delay, index) => {
      timers.push(
        setTimeout(() => {
          setAnimateItems((prev) => {
            const newAnimateItems = [...prev];
            newAnimateItems[index] = true;
            return newAnimateItems;
          });
        }, delay)
      );
    });

    return () => {
      clearTimeout(timer);
      timers.forEach((t) => clearTimeout(t));
    };
  }, []);

  return (
    <>
      <Head>
        <title>Impressive Resumes | Easy Online Builder</title>
        <meta
          name="description"
          content="Create professional resumes with our easy-to-use online resume builder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`flex h-screen bg-black text-white overflow-hidden border-2 border-white rounded-3xl m-5 p-5 ${
          isVisible ? "shadow-lg shadow-white/20" : ""
        }`}
      >
        {/* Left content section */}
        <div className="w-full md:w-1/2 px-8 md:px-16 flex flex-col justify-center">
          <div
            className={`transition-all duration-1000 transform ${
              isVisible
                ? "opacity-100 translate-y-0"
                : "opacity-0 translate-y-10"
            }`}
          >
            <h1
              className={`text-4xl md:text-5xl font-bold mb-2 ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-5"
              } transition-all duration-700 ease-out`}
            >
              IMPRESSIVE RESUMES
            </h1>
            <h2
              className={`text-3xl md:text-4xl font-bold mb-8 ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-5"
              } transition-all duration-700 ease-out delay-300`}
            >
              EASY ONLINE BUILDER
            </h2>

            <ul className="space-y-3 mb-8">
              <li
                className={`flex items-start ${
                  animateItems[0]
                    ? "opacity-100 translate-x-0"
                    : "opacity-0 translate-x-5"
                } transition-all duration-500 ease-out group`}
              >
                <svg
                  className="w-5 h-5 text-green-500 mr-2 mt-1 flex-shrink-0 group-hover:scale-125 transition-transform duration-300"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  ></path>
                </svg>
                <span className="text-sm md:text-base">
                  Professional out-of-the-box resumes, instantly generated by
                  the most advanced resume builder technology available.
                </span>
              </li>
              <li
                className={`flex items-start ${
                  animateItems[1]
                    ? "opacity-100 translate-x-0"
                    : "opacity-0 translate-x-5"
                } transition-all duration-500 ease-out group`}
              >
                <svg
                  className="w-5 h-5 text-green-500 mr-2 mt-1 flex-shrink-0 group-hover:scale-125 transition-transform duration-300"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  ></path>
                </svg>
                <span className="text-sm md:text-base">
                  Effortless crafting. Real-time preview & pre-written resume
                  examples.
                </span>
              </li>
              <li
                className={`flex items-start ${
                  animateItems[2]
                    ? "opacity-100 translate-x-0"
                    : "opacity-0 translate-x-5"
                } transition-all duration-500 ease-out group`}
              >
                <svg
                  className="w-5 h-5 text-green-500 mr-2 mt-1 flex-shrink-0 group-hover:scale-125 transition-transform duration-300"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  ></path>
                </svg>
                <span className="text-sm md:text-base">
                  Dozens of HR-approved resume templates.
                </span>
              </li>
              <li
                className={`flex items-start ${
                  animateItems[3]
                    ? "opacity-100 translate-x-0"
                    : "opacity-0 translate-x-5"
                } transition-all duration-500 ease-out group`}
              >
                <svg
                  className="w-5 h-5 text-green-500 mr-2 mt-1 flex-shrink-0 group-hover:scale-125 transition-transform duration-300"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  ></path>
                </svg>
                <span className="text-sm md:text-base">
                  Land your dream job with the perfect resume employers are
                  looking for.
                </span>
              </li>
            </ul>

            <button
              className={`bg-red-600 hover:bg-red-700 text-white font-bold py-3 px-6 rounded-md transition-all duration-300 ${
                isVisible ? "opacity-100 scale-100" : "opacity-0 scale-90"
              } ${hoverButton ? "shadow-lg shadow-red-500/50 scale-105" : ""}`}
              onClick={() => console.log("Start my resume clicked")}
              onMouseEnter={() => setHoverButton(true)}
              onMouseLeave={() => setHoverButton(false)}
            >
              START MY RESUME
            </button>
          </div>
        </div>

        {/* Illustration section */}
        <div className="hidden md:flex md:w-1/2 items-center justify-center relative">
          <div
            className={`transition-all duration-1000 transform ${
              isVisible
                ? "opacity-100 translate-y-0"
                : "opacity-0 translate-y-10"
            }`}
          >
            <img
              src="resume.png"
              alt="Resume template preview"
              className="max-w-full h-auto"
            />
          </div>
        </div>
      </div>
    </>
  );
}
